name: Deploy Flet App to EC2

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout del c贸digo
      - name: Checkout code
        uses: actions/checkout@v2

      # Configurar Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t flet-app .

      # Iniciar sesi贸n en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Subir la imagen a Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker tag flet-app:latest ${{ secrets.DOCKER_USERNAME }}/flet-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/flet-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Establecer la conexi贸n SSH a tu servidor EC2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      # Desplegar el contenedor en EC2
      - name: Deploy Docker container to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            # Iniciar sesi贸n y ejecutar Docker en EC2
            docker pull ${{ secrets.DOCKER_USERNAME }}/flet-app:latest
            docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/flet-app:latest
          EOF
